OnlineEducationAPP.MvcWebUI/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineEducationAPP.MvcWebUI.Identity;
using OnlineEducationAPP.MvcWebUI.Models;

namespace OnlineEducationAPP.MvcWebUI.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ProfileController(UserManager<ApplicationUser> userManager , IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Detail(string id)
        {

            var user = await _userManager.FindByIdAsync(id);
            var model = new UserEditViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                Email = user.Email,
                UserName = user.UserName,
                ProfileImageUrl = user.ProfileImageUrl,
                CarouselImageUrl = user.CarouselImageUrl
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (ModelState.IsValid)
            {

                var user = await _userManager.FindByIdAsync(model.Id);

                user.Name = model.Name;
                user.Surname = model.Surname;
                user.Email = model.Email;
                if(model.ProfilePhoto !=null)
                    user.ProfileImageUrl = ProcessUploadFile(model);

                await _userManager.UpdateAsync(user);

            }
            return RedirectToAction("Index","Dashboard");
        }

        private string ProcessUploadFile(UserEditViewModel model)
        {
            string result = null;
            if (model.ProfilePhoto != null)
            {
                var uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath + "\\app-assets\\images\\backgrounds");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfilePhoto.FileName;
                var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                model.ProfilePhoto.CopyTo(new FileStream(filePath, FileMode.Create));
                result = "/app-assets/images/backgrounds/" + uniqueFileName;
            }
            return result;
        }
    }
}

OnlineEducationAPP.MvcWebUI/Controllers/StreamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineEducationAPP.MvcWebUI.Entity;
using OnlineEducationAPP.MvcWebUI.Identity;
using OnlineEducationAPP.MvcWebUI.Repository.Abstract;

namespace OnlineEducationAPP.MvcWebUI.Controllers
{
    public class StreamController : Controller
    {
        private IUnitOfWork unitOfWork;
        private UserManager<ApplicationUser> _userManager;
        
        public StreamController(IUnitOfWork _unitOfWork, UserManager<ApplicationUser> userManager)
        {
            unitOfWork = _unitOfWork;
            _userManager = userManager;
        }
        [Authorize(Roles = "Teacher,Admin")]
        [Route("Stream/Create")]
        [HttpGet]
        public IActionResult Create()
        {

            var courses = unitOfWork.Courses.GetAll().ToList();
            return View(courses);
        }

        [Authorize(Roles = "Student,Teacher,Admin")]
        [Route("Stream/{Id}")]
        [HttpGet]
        public IActionResult Stream(int Id)
        {
            var stream = unitOfWork.Streams.Get(Id);
            stream.AmaountShown++;
            unitOfWork.SaveChanges();
            ViewBag.UserId = _userManager.GetUserId(User);
            return View(stream);
        }

        [Authorize(Roles = "Teacher,Admin")]
        [HttpPost]
        public dynamic Create(int courseId, string streamName)
        {
            var userID = _userManager.GetUserId(User);

            string streamKey = Guid.NewGuid().ToString();

            var model = new Stream
            {
                CourseId = courseId,
                StartTime = null,
                IsActive = false,
                StreamName = streamName,
                UserId = userID,
                LiveStreamEndpoint = "https://onlineeducationapp.canberkpolat.com:8443/live/",
                VideoOnDemandEndpoint = "https://onlineeducationapp.canberkpolat.com:8443/vod/",
                StreamKey = streamKey
            };
            unitOfWork.Streams.Add(model);
            unitOfWork.SaveChanges();

            var response = new
            {
                StreamEndPoint = "rmtp://onlineeducationapp.canberkpolat.com:8080/live",
                StreamKey = streamKey
            };

            return response;
        }

        [HttpPost]
        [Route("Stream/Start")]
        public void Start([FromForm] string name)
        {
            var stream = unitOfWork.Streams.Find(p => p.StreamKey == name && p.EndTime == null).FirstOrDefault();
            if(stream != null) { 
                stream.IsActive = true;
                stream.StartTime = DateTime.Now;

                unitOfWork.SaveChanges();
            }
            else
            {
                throw new Exception("Invalid stream key.");
            }
        }

        [HttpPost]
        [Route("Stream/Update")]
        public void Update([FromForm] string name)
        {
            var stream = unitOfWork.Streams.Find(p => p.StreamKey == name && p.EndTime == null).FirstOrDefault();
            if (stream != null)
            {
                stream.IsActive = true;
                stream.UpdateTime = DateTime.Now;

                unitOfWork.SaveChanges();
            }
            else
            {
                throw new Exception("Invalid stream key.");
            }
        }

        [HttpPost]
        [Route("Stream/End")]
        public void End([FromForm] string name)
        {
            var stream = unitOfWork.Streams.Find(p => p.StreamKey == name).FirstOrDefault();
            if (stream != null)
            {
                stream.IsActive = false;
                stream.EndTime = DateTime.Now;

                unitOfWork.SaveChanges();
            }
            else
            {
                throw new Exception("Invalid stream key.");
            }
        }
    }
}

OnlineEducationAPP.MvcWebUI/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
    Layout = null;
}
<partial name="_CssJsLinks" />
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <div class="col-sm-5 offset-sm-1 col-md-6 offset-md-3 col-lg-4 offset-lg-4 box-shadow-2" style="margin-top: 100px !important">
                    <div class="card border-grey border-lighten-3 px-2 my-0 row">
                        <div class="card-header no-border pb-1">
                            <div class="card-body">
                                <h2 class="error-code text-center mb-2">404</h2>
                                <h3 class="text-uppercase text-center">@ViewBag.ErrorMessage</h3>
                            </div>
                        </div>
                        <div class="card-content px-2">
                            <fieldset class="row py-1">
                                <div class="row py-2">
                                    <div class="col-12">
                                        <a href="/Dashboard/Index" class="btn btn-primary btn-block btn-lg"><i class="la la-home"></i> Back to Home</a>
                                    </div>
                                </div>
                            </fieldset>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

OnlineEducationAPP.MvcWebUI/Views/Shared/_CssJsLinks.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
<meta name="keywords" content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
<meta name="author" content="PIXINVENT">
<title>
    iziLearn
</title>

<link href="https://vjs.zencdn.net/7.6.6/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
<script src="https://vjs.zencdn.net/7.6.6/video.js"></script>

<link rel="apple-touch-icon" href="~/app-assets/images/ico/apple-icon-120.png">
<link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/ico/favicon.ico">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700"
      rel="stylesheet">
<link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css"
      rel="stylesheet">

<!--Full Calendear   -->
<link href="~/lib/fullcalendar-4.4.2/core/main.css" rel="stylesheet" />
<link href="~/lib/fullcalendar-4.4.2/daygrid/main.css" rel="stylesheet" />

<script src="~/lib/fullcalendar-4.4.2/core/main.js"></script>
<script src="~/lib/fullcalendar-4.4.2/interaction/main.js"></script>
<script src="~/lib/fullcalendar-4.4.2/daygrid/main.js"></script>

<!-- BEGIN VENDOR CSS-->


<link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/forms/selects/jquery.selectBoxIt.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/plugins/forms/selectBoxIt/selectBoxIt.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/vendors.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/weather-icons/climacons.min.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/fonts/meteocons/style.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/forms/icheck/icheck.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/forms/icheck/custom.css">
<!-- END VENDOR CSS-->
<!-- BEGIN MODERN CSS-->
<link rel="stylesheet" type="text/css" href="~/app-assets/css/app.css">
<!-- END MODERN CSS-->
<!-- BEGIN Page Level CSS-->
<link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/horizontal-menu.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/fonts/simple-line-icons/style.min.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/chat-application.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/error.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/timeline.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/dashboard-ecommerce.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/login-register.css">
<!-- END Page Level CSS-->
<!-- BEGIN Custom CSS-->
<link rel="stylesheet" type="text/css" href="~/assets/css/style.css">


<!-- BEGIN VENDOR JS-->
<script src="~/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment-with-locales.min.js"></script>
<script type="text/javascript" src="~/lib/datetimepicker/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" type="text/css" href="~/lib/datetimepicker/bootstrap-datetimepicker.css" />
<!-- BEGIN VENDOR JS-->
<!-- BEGIN PAGE VENDOR JS-->
<script type="text/javascript" src="~/app-assets/vendors/js/ui/jquery.sticky.js"></script>
<script src="~/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js" type="text/javascript"></script>
<script src="~/app-assets/vendors/js/forms/icheck/icheck.min.js" type="text/javascript"></script>
<script src="~/app-assets/vendors/js/charts/raphael-min.js" type="text/javascript"></script>
<script src="~/app-assets/vendors/js/timeline/horizontal-timeline.js" type="text/javascript"></script>
<!-- END PAGE VENDOR JS-->
<!-- BEGIN MODERN JS-->
<script src="~/app-assets/js/core/app-menu.js" type="text/javascript"></script>
<script src="~/app-assets/js/core/app.js" type="text/javascript"></script>
<script src="~/app-assets/js/core/libraries/jquery_ui/jquery-ui.min.js" type="text/javascript"></script>
<!-- END MODERN JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="~/app-assets/js/scripts/forms/form-login-register.js" type="text/javascript"></script>
<script src="~/app-assets/js/scripts/pages/chat-application.js" type="text/javascript"></script>
<script src="~/app-assets/vendors/js/forms/select/jquery.selectBoxIt.min.js" type="text/javascript"></script>

<script src="~/js/axios.min.js"></script>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<!-- END PAGE LEVEL JS-->

OnlineEducationAPP.MvcWebUI/Views/Shared/_FooterJSLinks.cshtml
<script src="~/js/chatlib.js"></script>
<script src="~/js/chat.js"></script>
`<script src="~/js/usernotification.js"></script>

OnlineEducationAPP.MvcWebUI/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<OnlineEducationAPP.MvcWebUI.Identity.ApplicationUser> UserManager
@{
    Layout = null;
}

<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item">
                    <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index">
                        <img src="~/home-page/img/iziLearn_logo.png" class="header-logo">
                    </a>
                </li>
                <li class="nav-item d-md-none">
                    <a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a>
                </li>
            </ul>
        </div>
        <div class="navbar-container container center-layout">
            <div class="collapse navbar-collapse" id="navbar-mobile">

                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item nav-search">
                        <form asp-controller="Dashboard" asp-action="Index" method="get">
                            <a class="nav-link nav-link-search"><i class="ficon ft-search"></i></a>
                            <div class="search-input">
                                <input class="input" type="text" name="searchString" value="" placeholder="Explore Online Classes...">
                            </div>
                        </form>

                    </li>
                </ul>

                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <span class="mr-1">
                                Hello,
                                <span class="user-name text-bold-700">@User.Identity.Name</span>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">

                            @if (User.IsInRole("Teacher"))
                            {
                                <a class="dropdown-item" asp-controller="Stream" asp-action="Create"><i class="la la-television"></i> Broadcast</a>

                            }
                            <a class="dropdown-item" asp-controller="Profile" asp-action="Detail" asp-route-id="@UserManager.GetUserId(User)"><i class="ft-user"></i>Profile</a>


                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout"><i class="ft-power"></i> Logout</a>
                            @if (User.IsInRole("Admin"))
                            {
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="GetCourses"><i class="la la-television"></i> Admin Page</a>
                            }


                        </div>
                    </li>

                    <li class="dropdown dropdown-notification nav-item">
                        <a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
                            <i class="ficon ft-bell"></i>
                            <span id="outerNoti" class="badge badge-pill badge-default badge-danger badge-default badge-up badge-glow"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <h6 class="dropdown-header m-0">
                                    <span class="grey darken-2">Notifications</span>
                                </h6>
                                <span id="innerNoti" class="notification-tag badge badge-default badge-danger float-right m-0"></span>
                            </li>
                            <li id="calendarNotification" class="scrollable-container media-list w-100">
                            </li>
                        </ul>
                    </li>
                    <partial name="_messageNotifications" />
                </ul>
            </div>
        </div>
    </div>
</nav>

OnlineEducationAPP.MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>

    <partial name="_CssJsLinks" />
</head>

<body class="horizontal-layout horizontal-menu 2-columns  menu-expanded pace-done" data-open="hover" data-menu="horizontal-menu" data-col="2-columns">
    <div class="pace pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>
    <partial name="_Header" />
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <partial name="_Navbar" />

    @RenderBody()
    <!-- ////////////////////////////////////////////////////////////////////////////-->
</body>
<partial name="_FooterJSLinks" />
</html>

OnlineEducationAPP.MvcWebUI/Views/Shared/_Navbar.cshtml
<div class="header-navbar navbar-expand-sm navbar navbar-horizontal navbar-fixed navbar-dark navbar-without-dd-arrow navbar-shadow"
        role="navigation" data-menu="menu-wrapper">
    <div class="navbar-container main-menu-content container center-layout" data-menu="menu-container">
        <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">

            <li class="dropdown nav-item" data-menu="dropdown">
                <a class="dropdown-toggle nav-link" href="/Dashboard/Index"><i class="la la-dashboard"></i><span>Dashboard</span></a>
            </li>
            <li class="dropdown nav-item" data-menu="dropdown">
                <a class="dropdown-toggle nav-link" href="/Dashboard/ActiveStreams"><i class="la la-television"></i><span>Active Streams</span></a>
            </li>
            @await Component.InvokeAsync("CourseList")
            <li class="dropdown nav-item" data-menu="dropdown">
                <a class="dropdown-toggle nav-link" href="/Calendar/Index"><i class="la la-calendar"></i><span>Calendar</span></a>

            </li>
            <li class="dropdown nav-item" data-menu="dropdown">
                <a class="dropdown-toggle nav-link" href="/Dashboard/Students"><i class="la la-group"></i><span>Students</span></a>

            </li>
            <li class="dropdown nav-item" data-menu="dropdown">
                <a class="dropdown-toggle nav-link" href="/Dashboard/Teachers" ><i class="la la-group"></i><span>Teachers</span></a>

            </li>
        </ul>
    </div>
</div>

OnlineEducationAPP.MvcWebUI/Views/Shared/_messageNotifications.cshtml
@await Component.InvokeAsync("MessageNotifications")